### PR TITLE
Anchor tags options

### PR DESCRIPTION
**Pull request by printscreen**
Purpose of this PR is to add in the ability to define attributes you want on anchor tags. The problem I am trying to solve is

1. Open links in a new tab (Solved in version 2.1.4)
2. Also protect against target="_blank" XSS attacks

To use this new attribute, it might look something like this
```
<template>
    <vue-markdown :anchorAttributes="anchorAttributes">{{ text }}</vue-markdown>
</template>
<script>
export default {
    data: () {
        anchorAttributes: {
            target: '_blank',
            rel: 'noopener noreferrer nofollow'
        }
    }
}
</script>
```

 Please comment with any suggestions or improvements you would like to see.

### CODE REVIEW

**Comment by printscreen** [comment]
@miaolz123  @nikolasp This is what I was thinking in my last comment.

**Comment by miaolz123** [comment]
@printscreen It look great !

Can I merge this PR into version 2.2.1 because this PR has a little break change ?

**Comment by printscreen** [comment]
Oh, that makes sense since i did replace a property, thus changing the API to the component. Yeah, it should have a minor version bump. You are right. You want me to make that change?

**Comment by miaolz123** [comment]
@printscreen I just think it'll be better to add an example in `./example/simple/index.html`.

**Comment by printscreen** [comment]
Ok, i will bump the version to 2.2.1 and update the `./example/simple/index.html` file

**Comment by miaolz123** [comment]
@printscreen yes, you can just change the version.

**Comment by miaolz123** [comment]
@printscreen and add you name at `Contributions` in `./README.md`.

**Comment by printscreen** [comment]
@miaolz123  Ok, updated

**Comment by nikolasp** [comment]
@printscreen This is great... Flexible and elegant solution.

**Pull request merged**
