### PR TITLE
adds task list support

### PR DESCRIPTION
**Pull request by LeFnord**

### CODE REVIEW

**Comment by miaolz123** [comment]
This is a great PR and I want to merge it, but it looks like something conflict after I update.

Can you update this PR ? thank you very much.

**Comment by LeFnord** [comment]
yeap, will fix it 😄

**Comment by LeFnord** [comment]
Sure, will have a look on it the next days

**Comment by miaolz123** [comment]
@LeFnord Thx~

**Comment by LeFnord** [comment]
@miaolz123 … done :)

**Pull request merged**
